set windows-shell := ["powershell.exe", "-NoLogo", "-NoProfile", "-Command"]

default:
	@just --list

run:
	@cargo run

run-debug $RUST_LOG="backend=debug,llm=debug,app_error=debug,info":
	@cargo run

run-info $RUST_LOG="info":
	@cargo run

alias debug := run-debug
alias info := run-info
